/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main_App;

import Service.Database;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author smart user
 */
public class Transaksi extends javax.swing.JFrame {

    private Database db = new Database();
    private ResultSet rs;
    private int indexBarang;
    private int row;
    private int harga;
    private int totalTransaksi;
    private int stok;
    private String idBarang;

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        FullScreen();
        SetDataBarang();
//        indexBarang = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Kode = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        JumlahBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TotalHargaBarang = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        TotalTransaksi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Pembayaran = new javax.swing.JTextField();
        Kembalian = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        Bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));

        jLabel1.setBackground(new java.awt.Color(20, 20, 20));
        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi");
        jLabel1.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Detail Barang");

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama Barang", "Harga", "Jumlah", "Total", "Hapus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTable1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(38, 38, 38));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kode");
        jPanel4.add(jLabel12);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Barang");
        jPanel4.add(jLabel4);

        Kode.setBackground(new java.awt.Color(51, 51, 51));
        Kode.setForeground(new java.awt.Color(204, 204, 204));
        Kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeActionPerformed(evt);
            }
        });
        Kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KodeKeyReleased(evt);
            }
        });
        jPanel4.add(Kode);

        NamaBarang.setBackground(new java.awt.Color(51, 51, 51));
        NamaBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NamaBarang.setForeground(new java.awt.Color(204, 204, 204));
        NamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarangActionPerformed(evt);
            }
        });
        NamaBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NamaBarangKeyReleased(evt);
            }
        });
        jPanel4.add(NamaBarang);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        jPanel4.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah Barang");
        jPanel4.add(jLabel6);

        Harga.setEditable(false);
        Harga.setBackground(new java.awt.Color(51, 51, 51));
        Harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Harga.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.add(Harga);

        JumlahBarang.setBackground(new java.awt.Color(51, 51, 51));
        JumlahBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JumlahBarang.setForeground(new java.awt.Color(204, 204, 204));
        JumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahBarangActionPerformed(evt);
            }
        });
        JumlahBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JumlahBarangKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JumlahBarangKeyReleased(evt);
            }
        });
        jPanel4.add(JumlahBarang);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Harga Barang");
        jPanel4.add(jLabel7);
        jPanel4.add(jLabel13);

        TotalHargaBarang.setEditable(false);
        TotalHargaBarang.setBackground(new java.awt.Color(51, 51, 51));
        TotalHargaBarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalHargaBarang.setForeground(new java.awt.Color(204, 204, 204));
        TotalHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaBarangActionPerformed(evt);
            }
        });
        jPanel4.add(TotalHargaBarang);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Tambah");
        jButton2.setMinimumSize(new java.awt.Dimension(0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jPanel5.setBackground(new java.awt.Color(38, 38, 38));
        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(51, 51, 51));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(204, 204, 204));
        jTextField5.setText("Total Harga");
        jPanel5.add(jTextField5);

        TotalTransaksi.setEditable(false);
        TotalTransaksi.setBackground(new java.awt.Color(51, 51, 51));
        TotalTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        TotalTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTransaksiActionPerformed(evt);
            }
        });
        jPanel5.add(TotalTransaksi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(38, 38, 38));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Input Barang");
        jLabel3.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cari");
        jLabel8.setMinimumSize(new java.awt.Dimension(0, 0));

        Search.setBackground(new java.awt.Color(51, 51, 51));
        Search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search.setForeground(new java.awt.Color(204, 204, 204));
        Search.setMinimumSize(new java.awt.Dimension(0, 0));
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });

        jScrollPane2.setMinimumSize(new java.awt.Dimension(0, 0));

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nama", "stok", "harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(102, 102, 102));
        jTable2.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTable2.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel7.setBackground(new java.awt.Color(38, 38, 38));
        jPanel7.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pembayaran");
        jLabel9.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel7.add(jLabel9);

        jPanel6.setBackground(new java.awt.Color(38, 38, 38));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pembayaran");
        jLabel10.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembalian");
        jLabel11.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.add(jLabel11);

        Pembayaran.setBackground(new java.awt.Color(51, 51, 51));
        Pembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Pembayaran.setForeground(new java.awt.Color(204, 204, 204));
        Pembayaran.setMinimumSize(new java.awt.Dimension(0, 0));
        Pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PembayaranKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PembayaranKeyReleased(evt);
            }
        });
        jPanel6.add(Pembayaran);

        Kembalian.setEditable(false);
        Kembalian.setBackground(new java.awt.Color(51, 51, 51));
        Kembalian.setForeground(new java.awt.Color(204, 204, 204));
        Kembalian.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.add(Kembalian);

        jPanel7.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(38, 38, 38));
        jPanel8.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        Bayar.setBackground(new java.awt.Color(51, 51, 51));
        Bayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Bayar.setForeground(new java.awt.Color(204, 204, 204));
        Bayar.setText("Bayar");
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        jPanel8.add(Bayar);

        jPanel7.add(jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1605, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Home_Karyawan.main(null);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaBarangActionPerformed

    private void JumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahBarangActionPerformed
        // TODO add your handling code here:
        jButton2.doClick();
    }//GEN-LAST:event_JumlahBarangActionPerformed

    private void JumlahBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBarangKeyReleased
        // TODO add your handling code here:
        try {

            int jumlahBarang = Integer.parseInt(JumlahBarang.getText());
//                JOptionPane.showMessageDialog(null, jumlahBarang > stok);
            if (jumlahBarang > stok) {
                JumlahBarang.setText(Integer.toString(stok));
                jumlahBarang = stok;
            } else {
                JumlahBarang.setEditable(true);
            }
            int jumlahHarga = jumlahBarang * harga;
            TotalHargaBarang.setText(Integer.toString(jumlahHarga));
        } catch (Exception e) {
            TotalHargaBarang.setText(Integer.toString(harga));
        }
    }//GEN-LAST:event_JumlahBarangKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String jmlhBarang = null;
        if (JumlahBarang.getText().isEmpty()) {
            jmlhBarang = "1";
        } else {
            jmlhBarang = JumlahBarang.getText();
        }
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();

//        int lenght = tbModel.getRowCount();
//        int totalHarga = Integer.parseInt(TotalHargaBarang.getText());
//        boolean addData = true;
//        if (lenght >= 0) {
//            for (int i = 0; i < lenght; i++) {
//                JOptionPane.showMessageDialog(null, i);
//                if (Integer.parseInt(idBarang) == Integer.parseInt((String) tbModel.getValueAt(0, i))) {
//                    JOptionPane.showMessageDialog(null, "A");
//                    jmlhBarang += tbModel.getValueAt(3, i);
//                    totalHarga = Integer.parseInt(TotalHargaBarang.getText()) + Integer.parseInt((String) tbModel.getValueAt(4, i));
//                    tbModel.setValueAt(jmlhBarang, 3, i);
//                    tbModel.setValueAt(Integer.toString(totalHarga), 4, i);
//                    addData = false;
//                } else {
//                    JOptionPane.showMessageDialog(null, "B");
//                    addData = true;
//                }
//            }
//        }
//        JOptionPane.showMessageDialog(null, addData);
//        if (addData) {
//            JOptionPane.showMessageDialog(null, "TES");TES
//            String[] tbData = {idBarang, NamaBarang.getText(), TotalHargaBarang.getText(), jmlhBarang, Integer.toString(totalHarga)};
//            tbModel.addRow(tbData);
//        }
//        totalTransaksi += Integer.parseInt(TotalHargaBarang.getText());
//        TotalTransaksi.setText(Integer.toString(totalTransaksi));
//        for (int i = 0; i < lenght; i++) {
//            try {
//                int totalHarga = Integer.parseInt(TotalHargaBarang.getText());
//                if (tbModel.getValueAt(0, i) == idBarang) {
//                    jmlhBarang += tbModel.getValueAt(3, i);
//                    totalHarga = Integer.parseInt(TotalHargaBarang.getText()) + Integer.parseInt((String) tbModel.getValueAt(4, i));
//                }
//                String[] tbData = {idBarang, NamaBarang.getText(), TotalHargaBarang.getText(), jmlhBarang, Integer.toString(totalHarga)};
//                totalTransaksi += Integer.parseInt(TotalHargaBarang.getText());
//                tbModel.addRow(tbData);
//                TotalTransaksi.setText(Integer.toString(totalTransaksi));
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, e);
//            }
        String[] tbData = {idBarang, NamaBarang.getText(), TotalHargaBarang.getText(), jmlhBarang, TotalHargaBarang.getText(), "Hapus?"};
        tbModel.addRow(tbData);
        totalTransaksi += Integer.parseInt(TotalHargaBarang.getText());
        TotalTransaksi.setText(Integer.toString(totalTransaksi));//        }

        tbModel = (DefaultTableModel) jTable2.getModel();
        int lenght = tbModel.getRowCount();
        for (int i = 0; i < lenght; i++) {
            try {
                tbModel.removeRow(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        SetDataBarang();
        Kode.setText("");
        NamaBarang.setText("");
        Harga.setText("");
        JumlahBarang.setText("");
        TotalHargaBarang.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JumlahBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBarangKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            JumlahBarang.setEditable(false);
        } else {
            JumlahBarang.setEditable(true);
        }
    }//GEN-LAST:event_JumlahBarangKeyPressed

    private void TotalTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTransaksiActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        // TODO add your handling code here:

        // Insert Transaction History
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        String idTransaksi = null;
        String query = "";
        try {
            query = "INSERT INTO transaksi VALUES(null, " + totalTransaksi + ", CURRENT_TIMESTAMP())";
            db.Query(query);
            db.AddData();
            query = "SELECT * FROM `transaksi` ORDER BY `id` DESC LIMIT 1;";
            db.Query(query);
            rs = db.resultSet();
            while (rs.next()) {
                idTransaksi = rs.getString("id");
            }
//            JOptionPane.showMessageDialog(null, rs.getString("id"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        // Insert Riwayat Barang
        int lenght = tbModel.getRowCount();
        for (int i = 0; i < lenght; i++) {
            try {
                String id = (String) tbModel.getValueAt(0, 0);
                String jmlh = (String) tbModel.getValueAt(0, 3);
                query = "INSERT INTO riwayat_barang VALUES(null, " + id + ", " + jmlh + ", 'Keluar', CURRENT_TIMESTAMP(), " + idTransaksi + ")";
                db.Query(query);
                db.AddData();

                // Update Stock
                query = "SELECT * FROM `barang` WHERE id = " + id;
                db.Query(query);
                rs = db.resultSet();
                while (rs.next()) {
                    id = rs.getString("id");
                    int sisaStok = rs.getInt("stok") - Integer.valueOf(jmlh);
                    query = "UPDATE barang SET stok = " + sisaStok + " WHERE id = " + id;
                    db.Query(query);
                    db.AddData();
                }
                tbModel.removeRow(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        // Refresh List Barang
        tbModel = (DefaultTableModel) jTable2.getModel();
        lenght = tbModel.getRowCount();
        for (int i = 0; i < lenght; i++) {
            try {
                tbModel.removeRow(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        SetDataBarang();

        NamaBarang.setText("");
        JumlahBarang.setText("");
        TotalHargaBarang.setText("");
        TotalTransaksi.setText("");
        Pembayaran.setText("");
        Kembalian.setText("");
    }//GEN-LAST:event_BayarActionPerformed

    private void PembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PembayaranKeyReleased
        // TODO add your handling code here:
        int kembalian = Integer.parseInt(Pembayaran.getText()) - totalTransaksi;
        if (kembalian < 0) {
            Kembalian.setText("Uang Tidak Cukup!!");
            Bayar.setEnabled(false);
        } else {
            Kembalian.setText(Integer.toString(kembalian));
            Bayar.setEnabled(true);
        }
    }//GEN-LAST:event_PembayaranKeyReleased

    private void PembayaranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PembayaranKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            JumlahBarang.setEditable(false);
        } else {
            JumlahBarang.setEditable(true);
        }
    }//GEN-LAST:event_PembayaranKeyPressed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();
        TableRowSorter<DefaultTableModel> srt = new TableRowSorter<>(tb);
        jTable2.setRowSorter(srt);
        srt.setRowFilter(RowFilter.regexFilter(Search.getText()));
    }//GEN-LAST:event_SearchKeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        row = jTable2.getSelectedRow();
        idBarang = jTable2.getModel().getValueAt(row, 0).toString();

        String query = "SELECT * FROM barang Where id = " + idBarang;
        db.Query(query);
        rs = db.resultSet();
        try {
            //            JOptionPane.showMessageDialog(null, tc);
            while (rs.next()) {
                Kode.setText(rs.getString("id"));
                NamaBarang.setText(rs.getString("nama_barang"));
                harga = Integer.parseInt(rs.getString("harga"));
                Harga.setText(Integer.toString(harga));
                TotalHargaBarang.setText(Integer.toString(harga));
                JumlahBarang.setText("");
                stok = Integer.parseInt(rs.getString("stok"));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        JumlahBarang.requestFocus();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();

        row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        if (column == 5) {

            totalTransaksi -= Integer.parseInt((String) tbModel.getValueAt(row, 4));
            TotalTransaksi.setText(Integer.toString(totalTransaksi));
            tbModel.removeRow(row);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void NamaBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamaBarangKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();
        int totalRow = tb.getRowCount();
        int col = tb.findColumn("nama");
        for (int i = 0; i < totalRow; i++) {
//            JOptionPane.showMessageDialog(null, tb.getValueAt(i, col).toString().toLowerCase());
            if (tb.getValueAt(i, col).toString().toLowerCase().equals(NamaBarang.getText().toLowerCase())) {
//                JOptionPane.showMessageDialog(null, tb.getValueAt(i, tb.findColumn("Id")).toString().toLowerCase());
                NamaBarang.setText(tb.getValueAt(i, tb.findColumn("nama")).toString().toLowerCase());
                Harga.setText(tb.getValueAt(i, tb.findColumn("harga")).toString().toLowerCase());
                stok = (int) tb.getValueAt(i, tb.findColumn("stok"));
                break;
            } else {
                NamaBarang.setText("");
                Harga.setText("");
            }

        }
    }//GEN-LAST:event_NamaBarangKeyReleased

    private void TotalHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaBarangActionPerformed

    private void KodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeActionPerformed
        // TODO add your handling code here:
        JumlahBarang.requestFocus();
    }//GEN-LAST:event_KodeActionPerformed

    private void KodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KodeKeyReleased
        // TODO add your handling code here:

        DefaultTableModel tb = (DefaultTableModel) jTable2.getModel();
        int totalRow = tb.getRowCount();
        int col = tb.findColumn("id");
        for (int i = 0; i < totalRow; i++) {
            if (tb.getValueAt(i, col).toString().toLowerCase().equals(Kode.getText().toLowerCase())) {
                NamaBarang.setText(tb.getValueAt(i, tb.findColumn("nama")).toString().toLowerCase());
                Harga.setText(tb.getValueAt(i, tb.findColumn("harga")).toString().toLowerCase());
                stok = (int) tb.getValueAt(i, tb.findColumn("stok"));
                JOptionPane.showMessageDialog(null, tb.getValueAt(i, tb.findColumn("stok")));
                break;
            } else {
                Harga.setText("");
                NamaBarang.setText("");
            }

        }
    }//GEN-LAST:event_KodeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    private void FullScreen() {
        getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        pack();
        setResizable(false);

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Point p = new Point(0, 0);
                SwingUtilities.convertPointToScreen(p, getContentPane());
                Point l = getLocation();
                l.x -= p.x;
                l.y -= p.y;
                setLocation(l);
            }
        });
    }

    private void SetDataBarang() {
        Database db = new Database();
        String query = "SELECT * FROM barang";
        db.Query(query);
        rs = db.resultSet();
        try {
            while (rs.next()) {
                String id = String.valueOf(rs.getLong("id"));
                String nama = rs.getString("nama_barang");
                String stok = rs.getString("stok");
                String harga = rs.getString("harga");

                String tbData[] = {id, nama, stok, harga};
                DefaultTableModel tbModel = (DefaultTableModel) jTable2.getModel();

                tbModel.addRow(tbData);
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bayar;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField JumlahBarang;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JTextField Kode;
    private javax.swing.JTextField NamaBarang;
    private javax.swing.JTextField Pembayaran;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField TotalHargaBarang;
    private javax.swing.JTextField TotalTransaksi;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
