/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import Service.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author smart user
 */
public class Supplier extends javax.swing.JPanel {

    private Database db = new Database();
    private ResultSet rs;

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        SetDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        KodeSupplier = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Telepon = new javax.swing.JTextField();
        Rekening = new javax.swing.JTextField();
        KodePos = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Alamat = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Fax = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        Tambah = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cari = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(38, 38, 38));

        jPanel19.setBackground(new java.awt.Color(38, 38, 38));
        jPanel19.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jPanel16.setBackground(new java.awt.Color(38, 38, 38));
        jPanel16.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jPanel14.setBackground(new java.awt.Color(38, 38, 38));
        jPanel14.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Kode");
        jPanel14.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nama");
        jPanel14.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Email");
        jPanel14.add(jLabel11);

        KodeSupplier.setBackground(new java.awt.Color(51, 51, 51));
        KodeSupplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KodeSupplier.setForeground(new java.awt.Color(204, 204, 204));
        KodeSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        KodeSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                KodeSupplierKeyReleased(evt);
            }
        });
        jPanel14.add(KodeSupplier);

        Nama.setBackground(new java.awt.Color(51, 51, 51));
        Nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nama.setForeground(new java.awt.Color(204, 204, 204));
        Nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(Nama);

        Email.setBackground(new java.awt.Color(51, 51, 51));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(204, 204, 204));
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(Email);

        jPanel16.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(38, 38, 38));
        jPanel15.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Telepon");
        jPanel15.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("No. Rekening");
        jPanel15.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Kode Pos");
        jPanel15.add(jLabel14);

        Telepon.setBackground(new java.awt.Color(51, 51, 51));
        Telepon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Telepon.setForeground(new java.awt.Color(204, 204, 204));
        Telepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.add(Telepon);

        Rekening.setBackground(new java.awt.Color(51, 51, 51));
        Rekening.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Rekening.setForeground(new java.awt.Color(204, 204, 204));
        Rekening.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.add(Rekening);

        KodePos.setBackground(new java.awt.Color(51, 51, 51));
        KodePos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KodePos.setForeground(new java.awt.Color(204, 204, 204));
        KodePos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.add(KodePos);

        jPanel16.add(jPanel15);

        jPanel19.add(jPanel16);

        jPanel18.setBackground(new java.awt.Color(38, 38, 38));
        jPanel18.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jPanel17.setBackground(new java.awt.Color(38, 38, 38));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Alamat");
        jLabel15.setMaximumSize(new java.awt.Dimension(99999, 99999));
        jLabel15.setPreferredSize(new java.awt.Dimension(43, 31));

        Alamat.setBackground(new java.awt.Color(51, 51, 51));
        Alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Alamat.setForeground(new java.awt.Color(204, 204, 204));
        Alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 1375, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alamat))
        );

        jPanel18.add(jPanel17);

        jPanel10.setBackground(new java.awt.Color(38, 38, 38));
        jPanel10.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jPanel7.setBackground(new java.awt.Color(38, 38, 38));
        jPanel7.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Fax");
        jPanel7.add(jLabel8);

        Fax.setBackground(new java.awt.Color(51, 51, 51));
        Fax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Fax.setForeground(new java.awt.Color(204, 204, 204));
        Fax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FaxKeyReleased(evt);
            }
        });
        jPanel7.add(Fax);

        jPanel10.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(38, 38, 38));
        jPanel9.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jPanel12.setBackground(new java.awt.Color(38, 38, 38));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(38, 38, 38));
        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        Tambah.setBackground(new java.awt.Color(51, 51, 51));
        Tambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tambah.setForeground(new java.awt.Color(204, 204, 204));
        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        jPanel13.add(Tambah);

        Edit.setBackground(new java.awt.Color(51, 51, 51));
        Edit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(204, 204, 204));
        Edit.setText("Edit");
        Edit.setEnabled(false);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel13.add(Edit);

        jPanel9.add(jPanel13);

        jPanel10.add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(38, 38, 38));
        jPanel11.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cari");
        jPanel11.add(jLabel1);

        Cari.setBackground(new java.awt.Color(51, 51, 51));
        Cari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cari.setForeground(new java.awt.Color(204, 204, 204));
        Cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CariKeyReleased(evt);
            }
        });
        jPanel11.add(Cari);

        jPanel10.add(jPanel11);

        jPanel18.add(jPanel10);

        jPanel19.add(jPanel18);

        jLabel16.setFont(new java.awt.Font("Cascadia Code", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Supplier");

        jTable1.setBackground(new java.awt.Color(51, 51, 51));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode", "Nama", "Email", "Telepon", "No. Rekening", "Kode Pos", "Alamat", "Fax"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTable1.setSelectionForeground(new java.awt.Color(204, 204, 204));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        String kode = KodeSupplier.getText();
        String nama = Nama.getText();
        String email = Email.getText();
        String telepon = Telepon.getText();
        String rekening = Rekening.getText();
        String pos = KodePos.getText();
        String alamat = Alamat.getText();
        String fax = Fax.getText();
        String query = "INSERT INTO supplier (id, kode, nama, email, telepon, rekening, kode_pos, alamat, fax) VALUES(null, '" + kode + "', '" + nama + "', '" + email + "', '" + telepon + "', '" + rekening + "', '" + pos + "', '" + alamat + "', '" + fax + "')";
        db.Query(query);
        if (db.AddData() > 0) {
            ClearTable();
            SetDataTable();
        }

        KodeSupplier.setText("");
        Nama.setText("");
        Email.setText("");
        Telepon.setText("");
        Rekening.setText("");
        KodePos.setText("");
        Alamat.setText("");
        Fax.setText("");
    }//GEN-LAST:event_TambahActionPerformed

    private void FaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FaxKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> srt = new TableRowSorter<>(tb);
        jTable1.setRowSorter(srt);
        srt.setRowFilter(RowFilter.regexFilter(Cari.getText()));
    }//GEN-LAST:event_FaxKeyReleased

    private void KodeSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KodeSupplierKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int col = tb.findColumn("Kode");
        int totalRow = tb.getRowCount();
        for (int i = 0; i < totalRow; i++) {
            if (tb.getValueAt(i, col).toString().toLowerCase().equals(KodeSupplier.getText().toLowerCase())) {
                //                JOptionPane.showMessageDialog(null, tb.getValueAt(i, tb.findColumn("Id")).toString().toLowerCase());
                Nama.setText(tb.getValueAt(i, tb.findColumn("Nama")).toString());
                Email.setText(tb.getValueAt(i, tb.findColumn("Email")).toString());
                Telepon.setText(tb.getValueAt(i, tb.findColumn("Telepon")).toString());
                Rekening.setText(tb.getValueAt(i, tb.findColumn("No. Rekening")).toString());
                KodePos.setText(tb.getValueAt(i, tb.findColumn("Kode Pos")).toString());
                Alamat.setText(tb.getValueAt(i, tb.findColumn("Alamat")).toString());
                Fax.setText(tb.getValueAt(i, tb.findColumn("Fax")).toString());
                Tambah.setEnabled(false);
                Edit.setEnabled(true);
                break;
            } else {
                Nama.setText("");
                Email.setText("");
                Telepon.setText("");
                Rekening.setText("");
                KodePos.setText("");
                Alamat.setText("");
                Fax.setText("");
                Tambah.setEnabled(true);
                Edit.setEnabled(false);
            }
        }
    }//GEN-LAST:event_KodeSupplierKeyReleased

    private void CariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> srt = new TableRowSorter<>(tb);
        jTable1.setRowSorter(srt);
        srt.setRowFilter(RowFilter.regexFilter(Cari.getText()));
    }//GEN-LAST:event_CariKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        KodeSupplier.setText(tb.getValueAt(row, tb.findColumn("Kode")).toString());
        Nama.setText(tb.getValueAt(row, tb.findColumn("Nama")).toString());
        Email.setText(tb.getValueAt(row, tb.findColumn("Email")).toString());
        Telepon.setText(tb.getValueAt(row, tb.findColumn("Telepon")).toString());
        Rekening.setText(tb.getValueAt(row, tb.findColumn("No. Rekening")).toString());
        KodePos.setText(tb.getValueAt(row, tb.findColumn("Kode Pos")).toString());
        Alamat.setText(tb.getValueAt(row, tb.findColumn("Alamat")).toString());
        Fax.setText(tb.getValueAt(row, tb.findColumn("Fax")).toString());
        Tambah.setEnabled(false);
        Edit.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        String kode = KodeSupplier.getText();
        String nama = Nama.getText();
        String email = Email.getText();
        String telepon = Telepon.getText();
        String rekening = Rekening.getText();
        String pos = KodePos.getText();
        String alamat = Alamat.getText();
        String fax = Fax.getText();

        String query = "UPDATE supplier SET nama = '" + nama + "', email = '" + email + "', telepon = '" + telepon + "', rekening = '" + rekening + "', kode_pos = '" + pos + "', alamat = '" + alamat + "', fax  = '" + fax + "' WHERE kode = '" + kode + "'";
        db.Query(query);
        if (db.AddData() > 0) {
            ClearTable();
            SetDataTable();
        }

        KodeSupplier.setText("");
        Nama.setText("");
        Email.setText("");
        Telepon.setText("");
        Rekening.setText("");
        KodePos.setText("");
        Alamat.setText("");
        Fax.setText("");
    }//GEN-LAST:event_EditActionPerformed

    private void SetDataTable() {
        String query = "SELECT * FROM supplier";
        db.Query(query);
        ResultSet rs = db.resultSet();
        try {
            int no = 0;

            while (rs.next()) {
                no++;
                String kode = rs.getString("kode");
                String nama = rs.getString("nama");
                String email = rs.getString("email");
                String telepon = rs.getString("telepon");
                String rekening = rs.getString("rekening");
                String kode_pos = rs.getString("kode_pos");
                String alamat = rs.getString("alamat");
                String fax = rs.getString("fax");

                String tbData[] = {Integer.toString(no), kode, nama, email, telepon, rekening, kode_pos, alamat, fax};
                DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();

                tbModel.addRow(tbData);
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void ClearTable() {
        DefaultTableModel tbModel = (DefaultTableModel) jTable1.getModel();
        int lenght = tbModel.getRowCount();
        for (int i = 0; i < lenght; i++) {
            try {
                tbModel.removeRow(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Cari;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fax;
    private javax.swing.JTextField KodePos;
    private javax.swing.JTextField KodeSupplier;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Rekening;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField Telepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
